/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class07;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        List<Integer> myArrayList = new ArrayList<>();
        myArrayList.add(5);

        for(int i = 0 ; i < myArrayList.size(); i++){
            System.out.println("array list at index " + i + ": " + myArrayList.get(i));
        }

    }
}
