/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test void RestaurantConstructorWorks(){
      //access
        Restaurant wendys = new Restaurant("Wendy's",5, 3 );
        String restaurantName = "I am a restaurant and this is my name: Wendy's";
        // act
        String actualOutput = wendys.nameOfRestaurant();
        // assert
        assertEquals(restaurantName, actualOutput);
    }

    @Test void reviewStringIsAccurate(){
        //access
        Review david = new Review("wendy's", 3, "David", "This Restaurant is the shit", 5 );
        String review1 = "Restaurant name: wendy's, Average stars: 5, Average Cost: 3, Author: David, Rating: 5, Review: This Restaurant is the shit";
        //act
        String actualOutput = david.reviewOfRestaurant();
        //assert
        assertEquals(actualOutput, review1);

    }

}
