/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test void RestaurantConstructorWorks(){
      //access
        Restaurant wendys = new Restaurant("Wendy's",5, 3 );
        String restaurantName = "Restaurant{" +
                "name='" + "Wendy's" + '\'' +
                ", stars=" + "5" +
                ", dollarSigns=" + "3" +
                '}';
        // act
        String actualOutput = wendys.toString();
        // assert
        assertEquals(restaurantName, actualOutput);
    }

    @Test void reviewStringIsAccurate(){
        //access
        Review david = new Review( "David",  "This Restaurant is the shit", 5 );
        String review1 = "Review{" +
                "body='This Restaurant is the shit" + '\'' +
                ", author='" + "David" + '\'' +
                ", stars=" + "5" +
                '}';
        //act
        String actualOutput = david.toString();
        //assert
        assertEquals(actualOutput, review1);

    }

    @Test void shopStringIsAccurate(){
        //access
        Shop dollarTree = new Shop("Dollar Tree","Buy some stuff!", 1);
        String shop = "Shop " +
                "dollarSigns = " + "1" +
                ", name = " + "Dollar Tree" + '\'' +
                ", description = " + "Buy some stuff!" + '\'';
        // act
        String actualOutput = dollarTree.toString();

        // assert
     assertEquals(actualOutput,shop);
    }

}
