/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.io.IOException;
import java.util.HashMap;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        Path alicePath = Paths.get( "alice_in_wonderland.txt");
        System.out.println(alicePath.toAbsolutePath());

        //Read the file
        Scanner scanner = null;
        scanner = new Scanner(alicePath);

        String characterName = "Alice";
        HashMap<String, Integer> aliceMap = new HashMap<>();
        aliceMap.put(characterName,0);

        while(scanner.hasNextLine()){
            String currentLine = scanner.nextLine();
            if(currentLine.contains(characterName)){
                aliceMap.put(characterName, (aliceMap.get(characterName) +1 ));
            }
        }

        System.out.println("Alice showed up in" + aliceMap.get(characterName) + "Lines");

        //Buffered Reader Example
        Path bufferedReaderalicePath = Paths.get( "alice_in_wanderland.txt");
        System.out.println(alicePath.toAbsolutePath());
    try{
        BufferedReader reader = Files.newBufferedReader(bufferedReaderalicePath);
        String line = reader.readLine();
        while(line != null){
            line = reader.readLine();
        }
    } catch(IOException ioe){
        System.out.println("Error reading file: " + ioe.getMessage());
        ioe.printStackTrace();
        }

    }
}
